Repository Dev-CasperTheGhost/snaily-cadv3, pull requests merged in 2021-05, with the labels that each got.

#175 Release 2.0.9
  docs/CHANGELOG.md
  package-lock.json
  package.json
  scripts/generate-lang.js
  src/components/modals/admin/penal-codes/CreatePenalCodeModal.tsx
  src/components/modals/admin/penal-codes/EditPenalCodeModal.tsx
  src/components/modals/citizen/RegisterWeaponModal.tsx
  src/components/modals/leo/NameSearchModal.tsx
  src/interfaces/Citizen.ts
  src/lib/database.ts
  src/pages/api/officer/citizen/[citizenId]/danger.ts
  src/pages/api/officer/citizen/[citizenId]/note.ts
  src/pages/citizen/[id]/edit.tsx
  src/pages/citizen/create.tsx
  src/state/items/officer/OfficerActions.ts
Labels: backend, bug fixes, dependencies, enhancement, frontend

#177 Release 2.0.10
  .dockerignore
  .eslintignore
  .eslintrc.json
  docker-compose.yml
  docs/CHANGELOG.md
  docs/CODE_OF_CONDUCT.md
  docs/SECURITY.md
  package.json
  public/fonts/Assistant-Bold.ttf
  public/fonts/Assistant-ExtraBold.ttf
  public/fonts/Assistant-Light.ttf
  public/fonts/Assistant-Medium.ttf
  public/fonts/Assistant-Regular.ttf
  public/fonts/Assistant-SemiBold.ttf
  scripts/generate-lang.js
  src/components/Select/selectStyles.ts
  src/components/modals/account/EditPasswordModal.tsx
  src/components/modals/admin/10-codes/Create10CodeModal.tsx
  src/components/modals/admin/10-codes/Edit10CodeModal.tsx
  src/components/modals/admin/AddValueModal.tsx
  src/components/modals/admin/EditValueModal.tsx
  src/components/modals/admin/penal-codes/CreatePenalCodeModal.tsx
  src/components/modals/admin/penal-codes/EditPenalCodeModal.tsx
  src/components/modals/citizen/EditLicensesModal.tsx
  src/components/modals/citizen/EditVehicleModal.tsx
  src/components/modals/citizen/RegisterVehicleModal.tsx
  src/components/modals/citizen/RegisterWeaponModal.tsx
  src/components/navbar/Navbar.tsx
  src/components/navbar/NavbarDropdown.tsx
  src/interfaces/Cad.ts
  src/lib/database.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/account/index.tsx
  src/pages/admin/cad-settings.tsx
  src/pages/admin/manage/members/[id].tsx
  src/pages/api/bleeter/[id].ts
  src/pages/api/global/cad-info/index.ts
  src/pages/citizen/[id]/edit.tsx
  src/pages/citizen/create.tsx
  src/pages/citizen/index.tsx
  src/styles/fonts.css
  src/styles/global.css
  tsconfig.json
Labels: backend, bug fixes, enhancement, frontend

#179 Release 2.0.11
  .github/ISSUE_TEMPLATE/bug_report.md
  docs/CHANGELOG.md
  package-lock.json
  package.json
  scripts/generate-lang.js
  src/components/dispatch/map/Map.tsx
  src/lib/utils.server.ts
  src/pages/api/calls/[type]/index.ts
  src/pages/api/citizen/[id]/index.ts
  src/pages/api/dispatch/calls/[id]/events.ts
  src/pages/api/dispatch/calls/[id]/index.ts
  src/pages/tow.tsx
  src/server.ts
Labels: backend, dependencies, enhancement, frontend

#180 Release 2.1.0
  .prettierrc.js
  docs/CHANGELOG.md
  package.json
  scripts/generate-lang.js
  src/components/Active911Calls/Active911Calls.tsx
  src/components/AlertMessage/AlertMessage.tsx
  src/components/admin/AdminSidebar.tsx
  src/components/admin/AllCitizens.tsx
  src/components/company/CreateCompanyModal.tsx
  src/components/company/JoinCompanyModal.tsx
  src/components/dispatch/ActiveCalls.tsx
  src/components/dispatch/map.ActiveCalls.tsx
  src/components/dispatch/map/Map.tsx
  src/components/ems-fd/Statuses.tsx
  src/components/leo/CreateWarrant.tsx
  src/components/leo/ModalButtons.tsx
  src/components/leo/Statuses.tsx
  src/components/modals/admin/10-codes/Create10CodeModal.tsx
  src/components/modals/admin/10-codes/Edit10CodeModal.tsx
  src/components/modals/admin/EditValueModal.tsx
  src/components/modals/admin/penal-codes/EditPenalCodeModal.tsx
  src/components/modals/citizen/EditLicensesModal.tsx
  src/components/modals/citizen/RegisterVehicleModal.tsx
  src/components/modals/citizen/RegisterWeaponModal.tsx
  src/components/modals/dispatch/Update911Call.tsx
  src/components/modals/ems-fd/SelectEmsFdModal.tsx
  src/components/modals/leo/CreateArrestReportModal.tsx
  src/components/modals/leo/CreateBoloModal.tsx
  src/components/modals/leo/CreateOfficerModal.tsx
  src/components/modals/leo/CreateTicketModal.tsx
  src/components/modals/leo/CreateWrittenWarningModal.tsx
  src/components/modals/leo/NameSearchModal.tsx
  src/components/modals/leo/SelectOfficerModal.tsx
  src/hooks/useAuth.ts
  src/interfaces/Cad.ts
  src/interfaces/Citizen.ts
  src/lib/database.ts
  src/lib/utils.ts
  src/pages/admin/cad-settings.tsx
  src/pages/admin/manage/units/[id].tsx
  src/pages/api/admin/members/[id]/index.ts
  src/pages/api/citizen/index.ts
  src/pages/api/dispatch/calls/[id]/index.ts
  src/pages/api/global/cad-info/index.ts
  src/pages/api/officer/[id]/status.ts
  src/pages/citizen/[id]/edit.tsx
  src/pages/citizen/create.tsx
  src/server.ts
  src/state/items/citizen/CitizenActions.ts
  tsconfig.json
Labels: backend, bug fixes, enhancement, frontend

#185 Release 2.1.3
  docs/CHANGELOG.md
  package.json
  scripts/generate-lang.js
  src/components/modals/account/EditUsernameModal.tsx
  src/components/modals/ems-fd/SelectEmsFdModal.tsx
  src/components/modals/leo/SelectOfficerModal.tsx
  src/components/modals/leo/UploadMugshotsModal.tsx
  src/interfaces/Cad.ts
  src/interfaces/ModalIds.ts
  src/interfaces/Tables.ts
  src/lib/database.ts
  src/pages/_document.tsx
  src/pages/account/index.tsx
  src/pages/admin/cad-settings.tsx
  src/pages/api/admin/10-codes/[id].ts
  src/pages/api/admin/10-codes/index.ts
  src/pages/api/auth/user/password.ts
  src/pages/api/auth/user/username.ts
  src/pages/api/companies/[id]/[employeeId].ts
  src/pages/api/companies/[id]/posts.ts
  src/pages/api/companies/index.ts
  src/pages/api/global/cad-info/index.ts
  src/state/items/auth/AuthActions.ts
  src/state/items/auth/AuthReducer.ts
  src/state/items/auth/AuthTypes.ts
Labels: backend, bug fixes, frontend

#186 Release 2.1.3-patch1
  .eslintrc.json
  docs/CHANGELOG.md
  package-lock.json
  package.json
  src/components/GlobalSearch/items.ts
  src/components/Seo.tsx
  src/components/dispatch/ActiveUnits.tsx
  src/components/dispatch/map/Map.tsx
  src/components/dispatch/map/blips.ts
  src/components/modals/leo/NameSearchModal.tsx
  src/config.example.ts
  src/hooks/useClientPerms.ts
  src/hooks/useSocket.ts
  src/interfaces/Map.ts
  src/interfaces/Socket.ts
  src/interfaces/State.ts
  src/interfaces/User.ts
  src/lib/socket.server.ts
  src/pages/api/bleeter/[id].ts
  src/pages/api/calls/[type]/index.ts
  src/pages/api/citizen/[id]/index.ts
  src/pages/api/citizen/index.ts
  src/pages/api/global/cad-info/features.ts
  src/pages/leo/dash.tsx
Labels: bug fixes, frontend

#189 Added in "nearest postal" function
  public/downloads/SnailyCADv3-911.zip
  public/downloads/SnailyCADv3-postal.zip
  public/downloads/SnailyCADv3-taxi.zip
  public/downloads/SnailyCADv3-tow.zip
Labels: enhancement, good first issue
