Repository Dev-CasperTheGhost/snaily-cadv3, pull requests merged in 2021-03, with the labels that each got.

#97 Release 1.3.8
  .github/dependabot.yml
  CHANGELOG.md
  client/package-lock.json
  client/package.json
  client/src/components/dispatch/map.ActiveCalls.tsx
  client/src/components/dispatch/map.ActiveUnits.tsx
  client/src/components/modals/ems-fd/searchMedicalRecords.tsx
  client/src/lib/actions/ems-fd.ts
  client/src/pages/citizen/index.tsx
  client/src/pages/dispatch/dash.tsx
  client/src/pages/dispatch/map.tsx
  client/src/pages/ems-fd/dash.tsx
  client/src/pages/leo/dash.tsx
  package.json
  server/config.example.ts
  server/package-lock.json
  server/package.json
Labels: backend, dependencies, frontend

#99 Release 1.3.9
  CHANGELOG.md
  client/src/components/AuthRoute.tsx
  client/src/components/leo/ModalButtons.tsx
  client/src/index.tsx
  client/src/interfaces/Officer.ts
  client/src/interfaces/User.ts
  client/src/lib/Logger.ts
  client/src/lib/actions/admin.ts
  client/src/pages/admin/management/members/manage-member.tsx
  client/src/pages/admin/management/officers/manage-officer.tsx
  client/src/pages/admin/management/officers/officers-management.tsx
  client/src/pages/leo/dash.tsx
  package.json
  server/.eslintrc.json
  server/src/hooks/useAuth.ts
  server/src/hooks/useMarkdown.ts
  server/src/hooks/usePermission.ts
  server/src/interfaces/IUser.ts
  server/src/interfaces/Officer.ts
  server/src/lib/constants.ts
  server/src/lib/database.ts
  server/src/lib/functions.ts
  server/src/routes/auth/index.ts
  server/src/routes/auth/steam.ts
  server/src/routes/bleeter.ts
  server/src/routes/citizen/index.ts
  server/src/routes/dispatch.ts
  server/src/routes/global.ts
  server/src/routes/management.ts
  server/src/routes/notifications.ts
  server/src/routes/officer.ts
  server/src/server.ts
  snaily-cad.sql
Labels: backend, enhancement, frontend

#111 Release 1.4.2
  CHANGELOG.md
  README.md
  client/public/index.html
  client/src/components/active-911-calls/index.tsx
  client/src/components/active-bolos/index.tsx
  client/src/components/admin/AdminLayout.tsx
  client/src/components/admin/AdminSidebar.tsx
  client/src/components/admin/all-citizens.tsx
  client/src/components/dispatch/ActiveCalls.tsx
  client/src/components/dispatch/ActiveUnits.tsx
  client/src/components/dispatch/ModalButtons.tsx
  client/src/components/dispatch/map.ActiveCalls.tsx
  client/src/components/dispatch/map.ActiveUnits.tsx
  client/src/components/ems-fd/Statuses.tsx
  client/src/components/global-search/index.tsx
  client/src/components/global-search/styles.css
  client/src/components/leo/CreateWarrant.tsx
  client/src/components/leo/ModalButtons.tsx
  client/src/components/leo/Statuses.tsx
  client/src/components/modals/ems-fd/searchMedicalRecords.tsx
  client/src/components/modals/leo/nameSearchModal.tsx
  client/src/interfaces/Citizen.ts
  client/src/interfaces/MedicalRecord.ts
  client/src/interfaces/Officer.ts
  client/src/lib/actions/admin.ts
  client/src/lib/actions/ems-fd.ts
  client/src/lib/actions/global.ts
  client/src/lib/functions.ts
  client/src/lib/socket.ts
  client/src/pages/admin/management/members/index.tsx
  client/src/pages/admin/management/officers/manage-officer.tsx
  client/src/pages/admin/management/officers/officers-management.tsx
  client/src/pages/admin/management/penal-codes/index.tsx
  client/src/pages/citizen/index.tsx
  client/src/pages/dispatch/dash.tsx
  client/src/pages/ems-fd/dash.tsx
  client/src/pages/leo/dash.tsx
  client/src/pages/leo/logs.tsx
  client/src/pages/tow/dash.tsx
  client/src/pages/truck-logs/dash.tsx
  client/src/styles/global.css
  package.json
  server/src/interfaces/Citizen.ts
  server/src/lib/checks.ts
  server/src/lib/constants.ts
  server/src/lib/database.ts
  server/src/lib/socket.ts
  server/src/routes/citizen/index.ts
  server/src/routes/ems-fd.ts
  server/src/routes/global.ts
  server/src/routes/management.ts
  server/src/routes/officer.ts
  snaily-cad.sql
Labels: backend, bug fixes, enhancement, frontend

#114 Release 1.4.4
  CHANGELOG.md
  README.md
  client/src/components/dispatch/ActiveCalls.tsx
  client/src/components/leo/CreateWarrant.tsx
  client/src/components/leo/Statuses.tsx
  client/src/components/modals/ems-fd/selectEmsFdModal.tsx
  client/src/components/modals/leo/createBoloModal.tsx
  client/src/components/modals/leo/nameSearchModal.tsx
  client/src/components/modals/leo/selectOfficerModal.tsx
  client/src/components/select/SelectStyles.tsx
  client/src/hooks/useObserver.ts
  client/src/index.tsx
  client/src/interfaces/State.ts
  client/src/lib/actions/911-calls.ts
  client/src/lib/actions/admin.ts
  client/src/lib/actions/auth.ts
  client/src/lib/actions/bleeter.ts
  client/src/lib/actions/ems-fd.ts
  client/src/lib/actions/officer.ts
  client/src/lib/actions/truck-logs.ts
  client/src/lib/actions/values.ts
  client/src/lib/functions.ts
  client/src/lib/reducers/adminReducer.ts
  client/src/lib/reducers/valuesReducer.ts
  client/src/lib/socket.ts
  client/src/lib/types.ts
  client/src/pages/admin/management/10-codes/index.tsx
  client/src/pages/admin/management/citizens/index.tsx
  client/src/pages/admin/management/members/index.tsx
  client/src/pages/admin/management/members/manage-member.tsx
  client/src/pages/admin/management/officers/manage-officer.tsx
  client/src/pages/admin/management/officers/officers-management.tsx
  client/src/pages/admin/management/penal-codes/index.tsx
  client/src/pages/admin/values/index.tsx
  client/src/pages/auth/register.tsx
  client/src/pages/citizen/create-citizen.tsx
  client/src/pages/citizen/edit-citizen.tsx
  client/src/pages/citizen/edit-licenses.tsx
  client/src/pages/citizen/medical-records/create-medical-record.tsx
  client/src/pages/citizen/vehicles/edit-vehicle.tsx
  client/src/pages/dispatch/map.tsx
  client/src/pages/ems-fd/create-deputy.tsx
  client/src/pages/ems-fd/dash.tsx
  client/src/pages/leo/create-officer.tsx
  client/src/pages/leo/dash.tsx
  client/src/pages/leo/penal-codes.tsx
  client/src/pages/truck-logs/create-truck-log.tsx
  package-lock.json
  package.json
  server/src/hooks/index.ts
  server/src/hooks/useSocketAuth.ts
  server/src/lib/socket.ts
  server/src/routes/citizen/company.ts
  server/src/routes/citizen/vehicles.ts
  server/src/routes/citizen/weapons.ts
  server/src/routes/global.ts
  server/src/routes/management.ts
  server/src/routes/officer.ts
Labels: backend, bug fixes, dependencies, enhancement, frontend

#117 Docker support
  .dockerignore
  Dockerfile
  docker-compose.yml
  server/config.example.ts
Labels: enhancement, good first issue

#118 Docker support (#117)
  .dockerignore
  Dockerfile
  docker-compose.yml
  server/config.example.ts
Labels: enhancement

#122 Release 1.4.6
  CHANGELOG.md
  Dockerfile
  client/public/index.html
  client/src/components/loader/index.tsx
  client/src/interfaces/State.ts
  client/src/lib/actions/dispatch.ts
  client/src/lib/functions.ts
  client/src/lib/reducers/dispatchReducer.ts
  client/src/pages/dispatch/map.tsx
  client/src/pages/leo/dash.tsx
  docker-compose.yml
  package.json
  server/src/api.ts
  server/src/hooks/useAuth.ts
  server/src/hooks/useSocketAuth.ts
  server/src/hooks/useToken.ts
  server/src/lib/config.ts
  server/src/lib/database.ts
  server/src/lib/socket.ts
  server/src/routes/dispatch.ts
  server/src/server.ts
Labels: backend, bug fixes, enhancement, frontend

#128 Release 1.4.7
  CHANGELOG.md
  Dockerfile
  client/src/components/active-911-calls/index.tsx
  client/src/components/admin/AdminSidebar.tsx
  client/src/components/admin/expungement-requests.tsx
  client/src/components/dispatch/ActiveCalls.tsx
  client/src/components/dispatch/map.ActiveCalls.tsx
  client/src/components/ems-fd/Statuses.tsx
  client/src/components/leo/Statuses.tsx
  client/src/components/modals/call911Modal.tsx
  client/src/components/modals/dispatch/Update911Call.tsx
  client/src/components/modals/dispatch/UpdateStatus.tsx
  client/src/components/navbar/index.tsx
  client/src/components/select/index.tsx
  client/src/index.tsx
  client/src/interfaces/Call.ts
  client/src/interfaces/Code10.ts
  client/src/interfaces/State.ts
  client/src/interfaces/ValuePaths.ts
  client/src/lib/actions/admin.ts
  client/src/lib/actions/global.ts
  client/src/lib/actions/values.ts
  client/src/lib/functions.ts
  client/src/lib/reducers/valuesReducer.ts
  client/src/lib/types.ts
  client/src/pages/admin/management/10-codes/add-code.tsx
  client/src/pages/admin/management/10-codes/edit-code.tsx
  client/src/pages/admin/management/10-codes/index.tsx
  client/src/pages/admin/management/penal-codes/index.tsx
  client/src/pages/admin/values/index.tsx
  client/src/pages/citizen/index.tsx
  client/src/pages/dispatch/map.tsx
  docker-compose.yml
  package.json
  scripts/generate-lang.js
  server/package-lock.json
  server/package.json
  server/src/hooks/useValidPath.ts
  server/src/lib/Logger.ts
  server/src/lib/database.ts
  server/src/monitoring-api.ts
  server/src/routes/dispatch.ts
  server/src/routes/global.ts
  server/src/routes/management.ts
  server/src/routes/monitoring/health.ts
  server/src/server.ts
  snaily-cad.sql
Labels: backend, bug fixes, enhancement, frontend
